global:
  evaluation_interval: 30s
  scrape_interval: 30s
  scrape_timeout: 10s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['prometheus:9090'] ## IP Address of the localhost. Match the port to your container port