// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: smr.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avoid  []*Avoid  `protobuf:"bytes,1,rep,name=avoid,proto3" json:"avoid,omitempty"`
	Number []*Number `protobuf:"bytes,2,rep,name=number,proto3" json:"number,omitempty"`
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_smr_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetAvoid() []*Avoid {
	if x != nil {
		return x.Avoid
	}
	return nil
}

func (x *DataRequest) GetNumber() []*Number {
	if x != nil {
		return x.Number
	}
	return nil
}

type DataNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string       `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ByFile bool         `protobuf:"varint,2,opt,name=by_file,json=byFile,proto3" json:"by_file,omitempty"`
	Number []*NumberAPI `protobuf:"bytes,3,rep,name=number,proto3" json:"number,omitempty"`
}

func (x *DataNumber) Reset() {
	*x = DataNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNumber) ProtoMessage() {}

func (x *DataNumber) ProtoReflect() protoreflect.Message {
	mi := &file_smr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNumber.ProtoReflect.Descriptor instead.
func (*DataNumber) Descriptor() ([]byte, []int) {
	return file_smr_proto_rawDescGZIP(), []int{1}
}

func (x *DataNumber) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataNumber) GetByFile() bool {
	if x != nil {
		return x.ByFile
	}
	return false
}

func (x *DataNumber) GetNumber() []*NumberAPI {
	if x != nil {
		return x.Number
	}
	return nil
}

type Avoid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Avoid) Reset() {
	*x = Avoid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Avoid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Avoid) ProtoMessage() {}

func (x *Avoid) ProtoReflect() protoreflect.Message {
	mi := &file_smr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Avoid.ProtoReflect.Descriptor instead.
func (*Avoid) Descriptor() ([]byte, []int) {
	return file_smr_proto_rawDescGZIP(), []int{2}
}

func (x *Avoid) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Number struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number    string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	TargetA2P uint32 `protobuf:"varint,2,opt,name=target_a2p,json=targetA2p,proto3" json:"target_a2p,omitempty"`
	TargetP2P uint32 `protobuf:"varint,3,opt,name=target_p2p,json=targetP2p,proto3" json:"target_p2p,omitempty"`
	Status    uint32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Number) Reset() {
	*x = Number{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_smr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_smr_proto_rawDescGZIP(), []int{3}
}

func (x *Number) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Number) GetTargetA2P() uint32 {
	if x != nil {
		return x.TargetA2P
	}
	return 0
}

func (x *Number) GetTargetP2P() uint32 {
	if x != nil {
		return x.TargetP2P
	}
	return 0
}

func (x *Number) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type NumberAPI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number  string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	RouteId uint32 `protobuf:"varint,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
}

func (x *NumberAPI) Reset() {
	*x = NumberAPI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberAPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberAPI) ProtoMessage() {}

func (x *NumberAPI) ProtoReflect() protoreflect.Message {
	mi := &file_smr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberAPI.ProtoReflect.Descriptor instead.
func (*NumberAPI) Descriptor() ([]byte, []int) {
	return file_smr_proto_rawDescGZIP(), []int{4}
}

func (x *NumberAPI) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *NumberAPI) GetRouteId() uint32 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

type DataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_smr_proto_rawDescGZIP(), []int{5}
}

func (x *DataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_smr_proto protoreflect.FileDescriptor

var file_smr_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0b, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x61, 0x76,
	0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x41, 0x76, 0x6f, 0x69,
	0x64, 0x52, 0x05, 0x61, 0x76, 0x6f, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x0a, 0x44, 0x61, 0x74,
	0x61, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x62,
	0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x62, 0x79,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x50, 0x49,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x05, 0x41, 0x76, 0x6f, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x76, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x61, 0x32, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x41, 0x32, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x70, 0x32, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x50, 0x32, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3e, 0x0a,
	0x09, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x50, 0x49, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x22, 0x28, 0x0a,
	0x0c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x80, 0x01, 0x0a, 0x07, 0x53, 0x6d, 0x72, 0x53,
	0x79, 0x6e, 0x63, 0x12, 0x27, 0x0a, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x0c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x09,
	0x73, 0x79, 0x6e, 0x63, 0x41, 0x76, 0x6f, 0x69, 0x64, 0x12, 0x06, 0x2e, 0x41, 0x76, 0x6f, 0x69,
	0x64, 0x1a, 0x0d, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x0b,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x0d, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x73, 0x79,
	0x6e, 0x63, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x73, 0x2d, 0x63, 0x61, 0x73,
	0x73, 0x2d, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smr_proto_rawDescOnce sync.Once
	file_smr_proto_rawDescData = file_smr_proto_rawDesc
)

func file_smr_proto_rawDescGZIP() []byte {
	file_smr_proto_rawDescOnce.Do(func() {
		file_smr_proto_rawDescData = protoimpl.X.CompressGZIP(file_smr_proto_rawDescData)
	})
	return file_smr_proto_rawDescData
}

var file_smr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_smr_proto_goTypes = []interface{}{
	(*DataRequest)(nil),  // 0: DataRequest
	(*DataNumber)(nil),   // 1: DataNumber
	(*Avoid)(nil),        // 2: Avoid
	(*Number)(nil),       // 3: Number
	(*NumberAPI)(nil),    // 4: NumberAPI
	(*DataResponse)(nil), // 5: DataResponse
}
var file_smr_proto_depIdxs = []int32{
	2, // 0: DataRequest.avoid:type_name -> Avoid
	3, // 1: DataRequest.number:type_name -> Number
	4, // 2: DataNumber.number:type_name -> NumberAPI
	0, // 3: SmrSync.syncData:input_type -> DataRequest
	2, // 4: SmrSync.syncAvoid:input_type -> Avoid
	1, // 5: SmrSync.syncNumber:input_type -> DataNumber
	5, // 6: SmrSync.syncData:output_type -> DataResponse
	5, // 7: SmrSync.syncAvoid:output_type -> DataResponse
	5, // 8: SmrSync.syncNumber:output_type -> DataResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_smr_proto_init() }
func file_smr_proto_init() {
	if File_smr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Avoid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Number); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberAPI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smr_proto_goTypes,
		DependencyIndexes: file_smr_proto_depIdxs,
		MessageInfos:      file_smr_proto_msgTypes,
	}.Build()
	File_smr_proto = out.File
	file_smr_proto_rawDesc = nil
	file_smr_proto_goTypes = nil
	file_smr_proto_depIdxs = nil
}
